

syntax on
"set mouse=a
set ai
set bs=indent,eol,start
set ruler
"set showmatch "关闭掉烦人的光标移动
set laststatus=2
set expandtab
set shiftwidth=4
set tabstop=4
set nu
set autoread
set noignorecase
set encoding=utf-8
set hls
"set foldmethod=syntax 
set t_Co=256
set nocompatible
filetype off
let mapleader=','

"colorscheme desert
"colorscheme molokai

"pathogen设置
"pathogen{
call pathogen#infect()
filetype plugin indent on
filetype plugin on
"}

"PowerLine配置
"PowerLine{
"let g:Powerline_symbols='fancy'
"}
"PowerLine配置

"taglist配置
"taglist{
let Tlist_Show_One_File = 1  "只显示当前文件的taglist
let Tlist_Exit_OnlyWindow = 1 "如果taglist是最后一个窗口就退出
let Tlist_Use_Right_Window = 1 "右侧显示taglist
let Tlist_GainFocus_On_ToggleOpen = 1 "打开taglist是光标保留在taglist窗口
let Tlist_Ctags_Cmd="/usr/bin/ctags"
let Tlist_Close_On_Select = 1 "选择tag后自动关闭taglist窗口
let Tlist_Auto_Open = 0 "设置taglist启动打开

"设置关闭打开taglist的快捷键
map tl : Tlist<CR>      

"}
"taglist配置

"syntastic配置
"syntastic{
let g:syntastic_check_on_open = 1
"}
"syntastic配置

"omni-completion
"{
set completeopt=longest,menu
"}
"omni-completion

let g:miniBufExplMapWindowNavArrows = 1

let g:molokai_original = 0

map <F7> :!ctags -R --c++-kinds=+px --fields=+aiSKz --extra=+q --langmap=c++:+.inl
map <F8> :cs add /root/util/cscope/cscope.out
map <unique> <tab> <Plug>Vm_goto_next_sign
nmap mn :!man <cword><CR>
set tags+=/usr/include/tags


